language: r
r:
- oldrel
- release
- devel
sudo: true
cache: packages

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libudunits2-dev

# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'

r_github_packages:
- ropensci/USAboundariesData

warnings_are_errors: true

notifications:
  slack:
    secure: F3ywEGAskqvJ6BlCXZgGPjUZkeSN+KRFbHpgKvVaMcf1nSMDfMSDS7X4rgGLLzHMu5lPbu/G69Hw7ousXFiO+b0cWShQcAK6xDYBGXs2MqmQLws3iFFnUKMjHQVwBpTcMPitsqU8gR27xWnC+Du5jzJ7amAO54LxfK3BPHm7cDg=
  email:
    on_success: never
    on_failure: always
